version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: welp-api
    ports:
      - "8080:8080"
      - "5050:5050"
    expose:
      - 8080
      - 5050
    environment:
      springdatasourceurl: jdbc:postgresql://psql:5432/welp?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      mypsqlpassword: password
      springdatasourceusername: postgres
      _JAVA_OPTIONS: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5050"
    depends_on:
      db:
        condition: service_healthy
    command: >-
      java -Djava.security.egd=file:/dev/./urandom -Dspring.jmx.enabled=false -XX:TieredStopAtLevel=1
      -Dspring.config.location=classpath:/application.properties -cp app:app/lib/* teamdanny.sideproject.welpapi.WelpApiApplication

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=welp
    container_name: psql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:



